### ISSUE TITLE
Bug na exibição do calendário.

### ISSUE THREAD

**Issue by esron** [Sysvale/board#11]
Como pode-se ver no destaque da imagem existe um pequeno deslocamento entre a primeira linha as linhas logo abaixo no calendário de impedimentos.

![image](https://user-images.githubusercontent.com/12296599/103919499-d91e1d00-50ee-11eb-9289-83152216104e.png)

Se precisar de mais informações é só pedri.

**Comment by geidsonc** [comment]
Este problema é da biblioteca calendar do vuetify.
Será resolvido na atualização do vuefity
